export const REQUEST_BALANCE = 'REAQUEST_BALANCE';
export const RECEIVE_BALANCE = 'RECEIVE_BALANCE';

export const REQUEST_DISPENSE = 'REQUEST_DISPENSE';
export const RECEIVE_DISPENSE = 'RECEIVE_DISPENSE';
export const ERROR_DISPENSE = 'ERROR_DISPENSE';
